"""empty message

Revision ID: 628006bf93fd
Revises: 0b6161857f59
Create Date: 2017-04-16 12:00:44.289000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628006bf93fd'
down_revision = '0b6161857f59'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('time_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'time_created')
    ### end Alembic commands ###
